//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Items = new HashSet<Item>();
        }
    
        public string ProductId { get; set; }
        public string CategoryId { get; set; }
        public string Name { get; set; }
        public string Descn { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
